/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface base {
  body?: any;
  query?: any;
  user?: {
    permissions?: any;
    username: string;
  };
}
