/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type calculateOdds = {
  odd: number;
  over: number;
  under: number;
}[];

export interface odd {
  odd: number;
  over: number;
  under: number;
}
