/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type calculateOdds = ({
  odd: number;
  over: number | any;
  under: number | any;
})[];

export type numberOrNullOrUndefined = number | any;

export interface odd {
  odd: number;
  over: number | any;
  under: number | any;
}
